export const ADD_PRODUCT = "ADD_PRODUCT"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"
export const QUANTITY_INCREMENT = "QUANTITY_INCREMENT"
export const QUANTITY_DECREMENT = "QUANTITY_DECREMENT"
export const START_PRICE_CHANGE = "START_PRICE_CHANGE"
export const END_PRICE_CHANGE = "END_PRICE_CHANGE"
export const APPLY_PRICE_FILTER = "APPLY_PRICE_FILTER"
export const APPLY_RATING_FILTER = "APPLY_RATING_FILTER"


